### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by iainsproat** [specklesystems/speckle-automate-github-action#2]
## Is your feature request related to a problem? Please describe.

When we log, we should be able to provide structured information, including error messages and stack traces.

## Describe the solution you'd like

Structured logging with pino.

We would create a custom transport for pino, this uses @actions/core logging from GitHub.

Our code would call a pino logger, and this would be configured with the pino-pretty transport, and our github transport:
`pino -> pino-pretty -> custom-transport`

## Additional context
- https://github.com/actions/toolkit/blob/master/packages/core/README.md
- https://github.com/pinojs/pino/blob/master/docs/transports.md

**Comment by gjedlicska** [comment]
for now the github logger is just fine imho
